# Generated by Django 5.0.6 on 2024-07-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimenovanie', models.CharField(max_length=250)),
                ('uchregdenie', models.CharField(max_length=250)),
                ('strana', models.CharField(max_length=30)),
                ('status_meropriatia', models.CharField(max_length=20)),
                ('status_uchastnikov', models.CharField(max_length=40)),
                ('data_podachi', models.DateField()),
                ('data_provedenia', models.DateField()),
                ('primechanie', models.CharField(max_length=250)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
