# Generated by Django 5.0.6 on 2024-07-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Podpiska',
        ),
    ]
