# Generated by Django 5.0.6 on 2024-07-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_users_podpiska'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podpiska',
            name='user_name',
        ),
    ]
