# Generated by Django 5.0.7 on 2024-07-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_podpiska_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ('-id',), 'verbose_name': 'Конференция', 'verbose_name_plural': 'Конференции'},
        ),
        migrations.AlterModelOptions(
            name='podpiska',
            options={'ordering': ('-id',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveField(
            model_name='conference',
            name='strana',
        ),
        migrations.AlterField(
            model_name='conference',
            name='data_podachi',
            field=models.DateField(verbose_name='Дата подачи'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='data_provedenia',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='naimenovanie',
            field=models.CharField(max_length=250, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='primechanie',
            field=models.CharField(max_length=250, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='status_meropriatia',
            field=models.CharField(max_length=20, verbose_name='Статус мероприятия'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='status_uchastnikov',
            field=models.CharField(max_length=40, verbose_name='Статус участников'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='uchregdenie',
            field=models.CharField(max_length=250, verbose_name='Учреждение'),
        ),
        migrations.AlterField(
            model_name='podpiska',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
    ]
