# Generated by Django 5.0.7 on 2024-07-27 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_country_alter_conference_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='strana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.country', verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
