# Generated by Django 5.0.7 on 2024-07-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_conference_strana'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Статус мероприятия')),
            ],
            options={
                'verbose_name': 'Статус мероприятия',
                'verbose_name_plural': 'Статусы мероприятия',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='conference',
            name='status_meropriatia',
        ),
    ]
