# Generated by Django 5.0.7 on 2024-07-27 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_eventstatus_remove_conference_status_meropriatia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Статус участника')),
            ],
            options={
                'verbose_name': 'Статус участника',
                'verbose_name_plural': 'Статусы участников',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='conference',
            name='status_uchastnikov',
        ),
        migrations.AddField(
            model_name='conference',
            name='status_meropriatia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.eventstatus', verbose_name='Статус мероприятия'),
        ),
    ]
