# Generated by Django 5.0.7 on 2024-07-27 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_participantstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='status_uchastnikov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.participantstatus', verbose_name='Статус участников'),
        ),
    ]
